### ISSUE TITLE
Settings: Add option "Account Wizard" which brings up the wizardscreen again from the ring-kde client

### ISSUE THREAD

**Issue by star-buck** [banji-project/ring-issues#4]
this option could be added in the menu bar -> Settings -> another entry "Account Wizard" at the bottom of the dropdown menu options

**Comment by Elv13** [comment]
![pick11](https://cloud.githubusercontent.com/assets/340384/25117922/0762aae8-23e2-11e7-977a-6b565f09f642.png)

Done

(as always for beta of any kde apps, `rm ~/.local/share/kxmlgui5/ring-kde/ring-kdeui.rc` may be necessary)

**Comment by star-buck** [comment]
Comes up nicely here.
To simplify and make consistent, in this case I would right away start with the Wizard page, and skip the welcome page layer, so this window comes up straight:
![screenshot_20170421_170035](https://cloud.githubusercontent.com/assets/840070/25283485/444bd07c-26b4-11e7-8f94-039add5733cb.png)

**Comment by star-buck** [comment]
@Elv13 : What about the last comment proposal?

**Comment by Elv13** [comment]
The wizard welcome page has been disabled as proposed

**Comment by star-buck** [comment]
So the welcome page has been disabled only in this case when directly invoked from menu, but it still shown normally while starting the client (with or without having an account already defined)?

**Comment by Elv13** [comment]
Correct. The splash screen replaced the wizard welcome page (as suggested). It is shown (unless disabled in the config) when the client launch (both the first and subsequent usage). The splash screen is not shown when invoked by the menu.

**Comment by star-buck** [comment]
> The splash screen replaced the wizard welcome page (as suggested).

This is not related to this ticket, but since you mention it here again:
There should not be another splash screen though, as the Welcome splash already IS a splash screen.

**Comment by Elv13** [comment]
Sorry if I misunderstood your original intent. While I did "unify" the splash screen, I did it the other way around. This can be fixed quickly.

Please note that technically, from a pure protocol point of view, the wizard isn't really considered a splash screen. I don't want to by pedantic here, but a splashscreen is "hardcoded"[1] into X11 (probably not in wayland) as a special window type designed for centered, frameless and volatile popup. The `QSplashScreen` isn't designed to do what you describe either. I can revert the commit and use the wizard popup on every startup and only show the first page. However, before doing so, I would like you to consider the following and take the decision:

 * It is uncommon for recent applications to use modal popups on each startup. KDE apps once had "tips of the day" popups, but this has been phased out.
 * Dialog type window are managed by the window manager and thus wont always be behaving as "expected" (even if the app request some settings, they can be ignored by the WM)
 * If the welcome popup is modal, then the client has to launch first. If it isn't modal, there can be overlapping issues. This problem is mostly mitigated by the fact that the popup would be hidden but will induce some [minor problems](https://specifications.freedesktop.org/startup-notification-spec/startup-notification-latest.txt) nevertheless.
 * Until the proposed local login feature is implemented (currently not scheduled), this popup serves little purpose beside looking pretty. From that point of view, isn't the current splashscreen better suited for that purpose.

[1] The WM (KWin) does the actual work, but the protocol specifies how

**Comment by star-buck** [comment]
lets go with the welcome splash as described #3 for several reasons 
(but also if only for the reason the other is X11-dependent anyway)

**Comment by star-buck** [comment]
here is how skype on linux always starts in the center, same size, even if you move it:
https://www.dropbox.com/s/gw7i9e1lsw4wnm1/skype-startscreen.mkv?dl=0

**Comment by star-buck** [comment]
since this ticket about the option to show the wizard again is solved, ill close this here now.
